name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]  # 🔥 Updated to only test on 3.12
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get latest Maigret commit hash
        id: maigret_ref
        run: |
          echo "SHA=$(git ls-remote https://github.com/soxoj/maigret.git HEAD | cut -f1)" >> $GITHUB_OUTPUT

      - name: Cache pip dependencies (including Maigret)
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-maigret-${{ steps.maigret_ref.outputs.SHA }}
          restore-keys: |
            ${{ runner.os }}-pip-maigret-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run tests with pytest
        run: |
          pip install pytest pytest-cov
          pytest --maxfail=1 --disable-warnings --cov=. --cov-report=xml
          echo "📂 Listing files:"
          ls -lah

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Create issue on test failure
        if: failure()
        # Pinning to commit cdb57ab6ff8862aa09fee2be6ba77a59581921c2 (v2)
        uses: dacbd/create-issue-action@cdb57ab6ff8862aa09fee2be6ba77a59581921c2

        with:
          title: "❌ CI Failure in `${{ github.workflow }}`"
          body: |
            Tests failed for commit `${{ github.sha }}` on branch `${{ github.ref_name }}`.
            Please investigate the failure. Workflow: `${{ github.workflow }}`.
          labels: bug, auto-generated
          token: ${{ secrets.GITHUB_TOKEN }}
