name: Sync Labels

on:
  push:
    paths:
      - ".github/labels.yml"
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  label-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync labels from .github/labels.yml
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a
        with:
          config-file: .github/labels.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
