# .github/workflows/stale.yml
name: Close Stale Issues and PRs

on:
  schedule:
    - cron: "0 1 * * *"  # Daily at 1 AM UTC

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: >
            This issue has been automatically marked as stale due to inactivity.
            It will be closed in 7 days if no further activity occurs.
          stale-pr-message: >
            This PR has been automatically marked as stale due to inactivity.
            It will be closed in 7 days if no further activity occurs.
          days-before-stale: 14
          days-before-close: 7
          exempt-issue-labels: "pinned,security"
          exempt-pr-labels: "pinned,security"
          operations-per-run: 100
